services:

  stat-server:
    build: ./stat-service/stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-service-db
    environment:
      - STAT_URL_DB=jdbc:postgresql://state_server-db:5432/statdb
      - STAT_USERNAME_DB=statdb
      - STAT_PASSWORD_DB=statdb


  stats-service-db:
    image: postgres:15-alpine
    container_name: stat-server-db
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_DB=statdb
      - POSTGRES_USER=statdb
      - POSTGRES_PASSWORD=statdb

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - MAIN_DB=jdbc:postgresql://postgres-main-db:5432/ewmdb
      - MAIN_USER=ewmdb
      - MAIN_PASSWORD=ewmdb

  ewm-db:
    image: postgres:15
    container_name: postgres-main-db
    ports:
      - "6464:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=ewmdb
      - POSTGRES_PASSWORD=ewmdb